adding list command and wait for command (hopefully fixed the typo)

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -59,12 +59,12 @@ jobs:
 
          status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)
           
-         if [ $status == "Sucsess" ] ; then
-          echo "Command executed successfully"
+         if [ $status == "Sucsess" ]; then
+           echo "Command executed successfully"
          else
-          echo "command failed"
-          echo "Error: $status"
-          exit 1
+           echo "command failed"
+           echo "Error: $status"
+           exit 1
           fi
 
         
