adding list command and wait for command (hopefully fixed the typo)

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -43,24 +43,29 @@ jobs:
         uses: aws-actions/amazon-ecr-login@v2
       - name: Deploy to EC2
         run: |
-          command_id =$(aws ssm send-command \
-           --document-name "AWS-RunShellScript" \
-           --targets "Key=instanceids,Values=i-07c2aa65dcdb16f9c,i-07d884ab7175cd83b" \
-           --comment "Pull Docker image and run it" \
-           --parameters commands='[
-            "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112619481.dkr.ecr.us-east-1.amazonaws.com"
-           ]' 
-            --query "Command.CommandId" --output text)
+         command_id=$(aws ssm send-command \
+         --document-name "AWS-RunShellScript" \
+         --targets "Key=instanceids,Values=i-07c2aa65dcdb16f9c,i-07d884ab7175cd83b" \
+         --comment "Pull Docker image and run it" \
+         --parameters commands='[
+           "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112619481.dkr.ecr.us-east-1.amazonaws.com"
+          ]' --query "Command.CommandId" --output text)
 
-           echo "$command_id"
+         echo "$command_id"
 
-           aws ssm wait command-executed \
-           --command-id $command_id \
-           --instance-id i-07c2aa65dcdb16f9c
+         aws ssm wait command-executed \
+         --command-id $command_id \
+         --instance-id i-07c2aa65dcdb16f9c
 
-           commandOutput=$(aws ssm list-commands --command-id $command_id)
+         status=$(aws ssm list-commands --command-id $command_id)
           
-           echo "$commandOutput"
+         if ["status" == "Sucsess"] ; then
+          echo "Command executed successfully"
+         else
+          echo "command failed"
+          echo "Error: $Status"
+          exit 1
+          fi
 
         
        
