removed some quotes

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -63,10 +63,12 @@ jobs:
 
           echo "$status"
 
-          if [ "$status" == "Success" ]; then 
+          if [ $status == "Success" ]; then 
             echo "Command executed successfully"
           else
             echo "Command failed"
+            echo "Error: "$status"
+            exit 1
           fi
 
           
