adding list command and wait for command (hopefully fixed the typo)

diff --git a/.github/workflows/main.yaml b/.github/workflows/main.yaml
--- a/.github/workflows/main.yaml
+++ b/.github/workflows/main.yaml
@@ -27,45 +27,46 @@ jobs:
   #         run: |
   #           docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
   #           docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
-  deploy:
-    name: Deploy to EC2
-    runs-on: ubuntu-latest
-   # needs: build-and-push-to-ecr
-    steps:
-      - name: Configure AWS credentials
-        uses: aws-actions/configure-aws-credentials@v4
-        with:
-          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
-          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-          aws-region: ${{secrets.AWS_REGION}}
-      - name: Login to Amazon ECR
-        id: login-aws-ecr
-        uses: aws-actions/amazon-ecr-login@v2
-      - name: Deploy to EC2
-        run: |
-         command_id=$(aws ssm send-command \
-         --document-name "AWS-RunShellScript" \
-         --targets "Key=instanceids,Values=i-07c2aa65dcdb16f9c,i-07d884ab7175cd83b" \
-         --comment "Pull Docker image and run it" \
-         --parameters commands='[
-           "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112619481.dkr.ecr.us-east-1.amazonaws.com"
-          ]' --query "Command.CommandId" --output text)
+ deploy:
+  name: Deploy to EC2
+  runs-on: ubuntu-latest
+  # needs: build-and-push-to-ecr
+  steps:
+    - name: Configure AWS credentials
+      uses: aws-actions/configure-aws-credentials@v4
+      with:
+        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        aws-region: ${{ secrets.AWS_REGION }}
 
-         echo "$command_id"
+    - name: Login to Amazon ECR
+      id: login-aws-ecr
+      uses: aws-actions/amazon-ecr-login@v2
 
-         aws ssm wait command-executed \
-         --command-id $command_id \
-         --instance-id i-07c2aa65dcdb16f9c
+    - name: Deploy to EC2
+      run: |
+        command_id=$(aws ssm send-command \
+          --document-name "AWS-RunShellScript" \
+          --targets "Key=instanceids,Values=i-07c2aa65dcdb16f9c,i-07d884ab7175cd83b" \
+          --comment "Pull Docker image and run it" \
+          --parameters 'commands=[
+            "aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 471112619481.dkr.ecr.us-east-1.amazonaws.com",
+            "docker pull 471112619481.dkr.ecr.us-east-1.amazonaws.com/cwc-ecr:latest",
+            "docker run --rm -p 3000:3000 471112619481.dkr.ecr.us-east-1.amazonaws.com/cwc-ecr:latest"
+          ]' \
+          --query "Command.CommandId" \
+          --output text)
 
-         status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].StatusDetails" --output text)
-          
-         if [ $status == "Sucsess" ]; then
-           echo "Command executed successfully"
-         else
-           echo "command failed"
-           echo "Error: $status"
-           exit 1
-          fi
+        aws ssm wait command-executed \
+          --command-id $command_id \
+          --instance-id i-07c2aa65dcdb16f9c
 
+        status=$(aws ssm list-commands --command-id $command_id --query "Commands[0].Status" --output text)
         
-       
+        if [ "$status" == "Success" ] ; then
+          echo "Command executed successfully"
+        else
+          echo "Command failed"
+          echo "Error: $status"
+          exit 1
+        fi
